name: Cypress Tests using Cypress Docker Image with allure-results

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write  # Add permission to write to GitHub Pages

jobs:
  Run_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm cy:run
        env:
          CYPRESS_username: ${{ secrets.TEST_USERNAME }}
          CYPRESS_password: ${{ secrets.TEST_PASSWORD }}

      - name: Generate Allure Report
        run: pnpm allure:report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report  # The directory containing the generated Allure report
          publish_branch: gh-pages  # The branch to deploy the report to
          cname: yourdomain.com  # Optional: your custom domain
