name: Cypress Tests using Cypress Docker Image with allure-results

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  Run_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Cypress tests
        run: pnpm cy:run

      - name: Create Allure report
        if: always()
        run: pnpm allure:report

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
            ref: allure
            path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            gh_pages: allure

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: allure
            publish_dir: allure-history
